# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d417d85a2f2e0fb4f940e533b0f1fd5043c8cd06538575c6cb0adcc93764b519ada96fb6802676b8f0f1127411b51a086082273732162c04cfaf2adf32400fb4

test:
  secret_key_base: 5c3243d6a430109a3ab613efeed0193619c5712e205cdb874cdfc2d55a98513ef45b6412edd7ddee87e20c07c68bb60a5e5b1d9a673f1ba5a2305a6d79a7e20f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
